  name: "evergreen"
  mode: "dev"
  start_time: "2023-01-01"
  machine_id: 1
  port: 8081

  log:
    level: "debug"
    filename: "evergreen.log"
    max_size: 300
    max_age: 30
    max_backups: 7

  mysql:
    host: "192.168.31.188"
    port: 13306
    user: "root"
    password: "root"
    dbname: "evergreen"
    max_open_conn: 500
    max_idle_conn: 5

  redis:
    host: "192.168.31.188"
    port: 16379
    pool_size: 50
    password: ""
    db: 0

  rabbitmq:
      host: "192.168.31.188"
      port: 5672
      user: "root"
      password: "root123"